### ISSUE TITLE
error: pnpx prisma generate

### ISSUE THREAD

**Issue by jayteen** [LeoKun1231/nest-prisma-template#1]
WARN  GET https://registry.npm.taobao.org/prisma error (CERT_HAS_EXPIRED). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npm.taobao.org/prisma error (CERT_HAS_EXPIRED). Will retry in 1 minute. 1 retries left.
F:\.pnpm-store\v3\tmp\dlx-9360:
 ERR_PNPM_META_FETCH_FAIL  GET https://registry.npm.taobao.org/prisma: request to https://registry.npm.taobao.org/prisma failed, reason: certificate has expired

This error happened while installing a direct dependency of F:\.pnpm-store\v3\tmp\dlx-9360

**Comment by LeoKun1231** [comment]
你好，这个应该是你淘宝镜像域名过期了，更换一下。

**Comment by jayteen** [comment]
> 你好，这个应该是你淘宝镜像域名过期了，更换一下。

是的，已经处理好了，谢谢
